### ISSUE TITLE
1.3.3. Record down minutes for the client meeting

### ISSUE THREAD

**Issue by ruihengg** [jiazheeeee/ICT-2201-Team-Project-Pharmacy-Shop-Work-Management-System#1]
Below contains the minutes taken for the first client meeting.

**Comment by ruihengg** [comment]
[Client Meeting Minutes 13Sep2022.pdf](https://github.com/jiazheeeee/ICT2201-P1-2-Team-Project-Pharmacy-Shop-Work-Management-System/files/9557143/Client.Meeting.Minutes.13Sep2022.pdf)

**Comment by jiazheeeee** [comment]
Reviewed by the team during lab lesson.

**Comment by ruihengg** [comment]
Done and reviewed by team during lab lesson, closed
