### ISSUE TITLE
1.4.1. Identify non functional requirements after analysing the project requirements

### ISSUE THREAD

**Issue by xAdwww** [jiazheeeee/ICT-2201-Team-Project-Pharmacy-Shop-Work-Management-System#12]
Find as much Non functional requirements as we can for the project before meeting the client to ensure we fully utilize the session.

**Comment by xAdwww** [comment]
Finished on 11th Sept 2022.


![Image](https://user-images.githubusercontent.com/90139442/191894140-fbf782a5-b4e4-4277-a582-d6f48131d9a6.png)

**Comment by jiazheeeee** [comment]
Reviewed and completed by the team during lab lesson.

**Comment by xAdwww** [comment]
Reviewed and closed.
