### ISSUE TITLE
1.1.4. & 1.1.5 Craft requirements gathering questions and make a simple prototype

### ISSUE THREAD

**Issue by xAdwww** [jiazheeeee/ICT-2201-Team-Project-Pharmacy-Shop-Work-Management-System#13]
Crafting of questions to ask during the face-to-face session with client and also a simple prototype to show the work allocation of users.

**Comment by xAdwww** [comment]
Done on 8th Sept 2022 by @mushroom-hat  as shown


![Image](https://user-images.githubusercontent.com/90139442/191894813-4d81752b-2f4b-43a5-aed3-90d7c8698a51.png)


![Image](https://user-images.githubusercontent.com/90139442/191894849-c93bbdb6-3dc8-411c-ae61-11d8756fc54f.png)

**Comment by xAdwww** [comment]
Requirements gathering questions by the team on 6~8 Sept 2022

![Image](https://user-images.githubusercontent.com/90139442/191895787-76c3ad12-9b30-42a1-baf4-dfbcde52146c.png)

**Comment by jiazheeeee** [comment]
Reviewed and completed by the team during lab lesson.

**Comment by xAdwww** [comment]
Reviewed and closed.
