### ISSUE TITLE
1.6.1.1. Calculate of TCF and EF

### ISSUE THREAD

**Issue by xAdwww** [jiazheeeee/ICT-2201-Team-Project-Pharmacy-Shop-Work-Management-System#14]
After confirming our requirements calculate the TCF and EF to help with the estimation of project.

**Comment by xAdwww** [comment]
After solidifying our requirements on 20th Sept 2022 we have calculated the TCF and EF as shown

![Image](https://user-images.githubusercontent.com/90139442/191893789-33319ccb-d48d-45e2-bb43-b2dde060ac77.png)

**Comment by jiazheeeee** [comment]
Reviewed and completed by the team during lab lesson.

**Comment by xAdwww** [comment]
Reviewed and closed.
