### ISSUE TITLE
1.3.3. Client Meeting 1 (Requirements Gathering)

### ISSUE THREAD

**Issue by xAdwww** [jiazheeeee/ICT-2201-Team-Project-Pharmacy-Shop-Work-Management-System#15]
Have a face-to-face interview with the client on 13 Sept 2022 to ensure that the requirements are assumed correctly and both parties on the same page.

**Comment by xAdwww** [comment]
after clarifying with the client on 13 Sept 2022 we have better understanding of the requirements prototype was shown and in response client was satisfied with it.

**Comment by jiazheeeee** [comment]
Reviewed and completed by the team during lab lesson.

**Comment by xAdwww** [comment]
Reviewed and closed.
