### ISSUE TITLE
1.3.2. Research on related background literature

### ISSUE THREAD

**Issue by xAdwww** [jiazheeeee/ICT-2201-Team-Project-Pharmacy-Shop-Work-Management-System#16]
Research related background literature for the M1 report

**Comment by xAdwww** [comment]
Done up the researching on 20th Sept 2022

https://hbr.org/2015/08/the-research-is-clear-long-hours-backfire-for-people-and-for-companies

https://blog.vantagecircle.com/efficient-organization/

**Comment by jiazheeeee** [comment]
Completed by the team during lesson.

**Comment by xAdwww** [comment]
Reviewed and closed.
