### ISSUE TITLE
1.4.5. Complete the use case diagram by analysing the project function requirements

### ISSUE THREAD

**Issue by xAdwww** [jiazheeeee/ICT-2201-Team-Project-Pharmacy-Shop-Work-Management-System#20]
Come up with a use case diagram for the M1 report after having our functional requirements finalized

**Comment by xAdwww** [comment]
Initial draft done on 16th Sept 2022 as shown

![Image](https://user-images.githubusercontent.com/90139442/191894997-8f5fcd1f-1b78-4780-a518-d4f5d1504f6a.png)

**Comment by xAdwww** [comment]
After discussing we realise that it doesn't seem to be right hence we reworked it and this is the finalized product done on 20 Sept 2022

![Image](https://user-images.githubusercontent.com/90139442/191895132-f3706242-a4ca-477f-b544-fdd2d35f8337.png)

**Comment by jiazheeeee** [comment]
Reviewed by the team during lab lesson.

**Comment by xAdwww** [comment]
Reviewed and closed.
