### ISSUE TITLE
1.4.4. Complete the use case description for the functional requirements

### ISSUE THREAD

**Issue by xAdwww** [jiazheeeee/ICT-2201-Team-Project-Pharmacy-Shop-Work-Management-System#21]
Do the use case description after meeting the client so that no double work is involve for the requirements.

**Comment by xAdwww** [comment]
(For sake of simplicity not showing everything only a part of it) 
First draft on 14th Sept 2022 as shown 


![Image](https://user-images.githubusercontent.com/90139442/191894379-d18ae6db-23c4-490b-8e1b-2abd63c48700.png)

**Comment by xAdwww** [comment]
(For sake of simplicity not showing everything only a part of it) 
Finished the use case description on 20th Sept 2022 as shown

![Image](https://user-images.githubusercontent.com/90139442/191894447-76d31185-9bad-4ed2-b7e9-55e28d004a60.png)

![Image](https://user-images.githubusercontent.com/90139442/191894484-9dc5d50c-9fb5-4a26-a430-b5b1bc1f3455.png)

**Comment by jiazheeeee** [comment]
Reviewed and completed by the team during lab lesson.

**Comment by xAdwww** [comment]
Reviewed and closed.
