### ISSUE TITLE
1.7.2. Work on Class Diagram

### ISSUE THREAD

**Issue by ruihengg** [jiazheeeee/ICT-2201-Team-Project-Pharmacy-Shop-Work-Management-System#24]

**Comment by mushroom-hat** [comment]
Class Diagram is essential for product analysis and design

**Comment by xAdwww** [comment]
Have to come up with Entity class, Control class and Boundary class.

**Comment by xAdwww** [comment]
This is the first draft of class diagram i came up with only consisting entity and control classes do add on!

October 11 2022

![Image](https://user-images.githubusercontent.com/90139442/195183089-7bba1168-0cfd-4082-8a92-80d045e170ec.png)

**Comment by xAdwww** [comment]
added some slight additions

October 11 2022

![Image](https://user-images.githubusercontent.com/90139442/195188381-5d89e9af-4470-4f32-b0c8-29b5bfe34f40.png)

**Comment by xAdwww** [comment]
Further revisions

October 16 2022

![Image](https://user-images.githubusercontent.com/90139442/196037773-3e3a175f-86ac-474c-87d3-1c577e154231.png)

**Comment by xAdwww** [comment]
In the midst of doing sequence diagram realised made some changes on class diagram.

18 October 2022

![Image](https://user-images.githubusercontent.com/90139442/196414533-660b1405-bddb-4400-a893-06fcfc8035ad.png)

**Comment by jiazheeeee** [comment]
This is the updated class diagram

![Image](https://user-images.githubusercontent.com/88085142/198294318-3d11eb6b-30a8-429f-9b46-155da39630f4.png)

**Comment by ruihengg** [comment]
Reviewed and closed.
