### ISSUE TITLE
1.5.1. Create a system architecture diagram

### ISSUE THREAD

**Issue by xAdwww** [jiazheeeee/ICT-2201-Team-Project-Pharmacy-Shop-Work-Management-System#26]
Come up with  a system architecture diagram that showcases how user interact with our system.

**Comment by xAdwww** [comment]
Done up the System Architecture diagram on 20th Sept 2022

![Image](https://user-images.githubusercontent.com/90139442/191892424-8ad562d7-ef0c-4889-bb06-5aaaee66513e.png)

**Comment by jiazheeeee** [comment]
Reviewed by the team during lesson.

**Comment by xAdwww** [comment]
Reviewed and closed.
