### ISSUE TITLE
1.5.1. Formatting of M1 report

### ISSUE THREAD

**Issue by xAdwww** [jiazheeeee/ICT-2201-Team-Project-Pharmacy-Shop-Work-Management-System#28]
After finalizing the contents of the report format it nicely so that it is presentable.

**Comment by xAdwww** [comment]
Done on 22th Sept 2022 formatting the report. Howeverr still have some sessions that requires input of info will be done before 24th Sept 2022.

**Comment by jiazheeeee** [comment]
Reviewed and completed by the team during lab lesson.

**Comment by xAdwww** [comment]
Reviewed and closed.
