### ISSUE TITLE
1.5.1. Writing requirements elicitation methods

### ISSUE THREAD

**Issue by xAdwww** [jiazheeeee/ICT-2201-Team-Project-Pharmacy-Shop-Work-Management-System#29]
Document down in M1 report the usage of requirement elicitation methods during our face-to-face session with the client.

**Comment by xAdwww** [comment]
Done writing down the requirement elicitation methods on 22 Sept 2022.

![Image](https://user-images.githubusercontent.com/90139442/191893620-e12278d5-7278-4884-ad9f-ea767f341dc9.png)

**Comment by jiazheeeee** [comment]
Reviewed and completed by the team during lab lesson.

**Comment by xAdwww** [comment]
Reviewed and closed.
