### ISSUE TITLE
1.3.3. Check if there are only 3 roles as of current Admin, Manager, and Staff.

### ISSUE THREAD

**Issue by xAdwww** [jiazheeeee/ICT-2201-Team-Project-Pharmacy-Shop-Work-Management-System#3]
Update: Verified that there is General manager, Normal manager, assistant manager, staff and admin.

**Comment by jiazheeeee** [comment]
Reviewed by the team during lab lesson.

**Comment by xAdwww** [comment]
Reviewed and closed.
