### ISSUE TITLE
1.8.5 Work on Sequence diagram

### ISSUE THREAD

**Issue by xAdwww** [jiazheeeee/ICT-2201-Team-Project-Pharmacy-Shop-Work-Management-System#31]
For each use case description we have to convert them into sequence diagram.

**Comment by xAdwww** [comment]
Login Use case description's sequence diagram

18 October 2022

![Image](https://user-images.githubusercontent.com/90139442/196379962-698464fd-ff93-496d-975a-f65177353475.png)

**Comment by xAdwww** [comment]
Logout Use case description's sequence diagram

18 October 2022

![Image](https://user-images.githubusercontent.com/90139442/196380103-7a46df27-bfcc-4ee1-8777-645c945cb1ff.png)

**Comment by xAdwww** [comment]
Creation of account use case description's sequence diagram

18 October 2022

![Image](https://user-images.githubusercontent.com/90139442/196385415-445e53f7-c67a-46e7-8680-ee990c84ca17.png)

**Comment by xAdwww** [comment]
Deletion of account use case description's sequence diagram

18 October 2022

![Image](https://user-images.githubusercontent.com/90139442/196387794-d5b8736d-3eb2-4e41-b4ee-f153c4697a46.png)

**Comment by xAdwww** [comment]
View all work allocation Use case description's sequence diagram

18 October 2022

![Image](https://user-images.githubusercontent.com/90139442/196413186-c0d49492-758d-420c-9629-2fe80ffaaef2.png)

**Comment by xAdwww** [comment]
Approve Job Use case description's sequence diagram

18 October 2022

![Image](https://user-images.githubusercontent.com/90139442/196438473-b475800f-a25e-4978-ad42-ca0c15e79811.png)

**Comment by xAdwww** [comment]
Branch Allocation Use case description's sequence diagram
Not too sure how to approach this do review and help to correct the diagram!

18 October 2022

![Image](https://user-images.githubusercontent.com/90139442/196438604-e6cfd5cc-ff89-4c72-82bd-c91ebaf3196c.png)

**Comment by mushroom-hat** [comment]
@xAdwww I have edited the Branch Allocation sequence diagram, I think its more suitable now, let me know your thoughts.

![Image](https://user-images.githubusercontent.com/88775203/196740296-29dcf411-a815-45af-b63f-a329d5d96b28.png)

**Comment by jiazheeeee** [comment]
@xAdwww I have updated the Create Account Sequence Diagram.


![Image](https://user-images.githubusercontent.com/88085142/198294692-0d44c21b-297f-4e02-af0a-8990cafe9ca1.png)

**Comment by xAdwww** [comment]
Reviewed the updated sequence diagram. All seems to be good, closing issue.

29 October 2022
