### ISSUE TITLE
1.4.5. Improve on the Use Case diagram as per feedback from M1

### ISSUE THREAD

**Issue by xAdwww** [jiazheeeee/ICT-2201-Team-Project-Pharmacy-Shop-Work-Management-System#32]
- Functionality bubbles should remove the page as it should only be from a functionality point of view.
- Actors can be generalised in our case General Manager, Normal Manager and Assistant Manager generalised as Managers.
- Just list out all the possible functionalities and then link them to the respective actors, ignore the messiness first.
- After done linking then try to tidy up.

**Comment by xAdwww** [comment]
This is the first draft i have done up do help review for mistakes i might have missed out



![Image](https://user-images.githubusercontent.com/90139442/193754412-7f2a5eab-3cae-4ac0-bb35-8528fd7aa611.png)

**Comment by xAdwww** [comment]
After discussion with the team this is the final revised copy of our Use Case Diagram

![Image](https://user-images.githubusercontent.com/90139442/195524894-e869e3bb-297a-4298-b363-13e0262a4103.png)

Date: 13 Oct 2022

**Comment by jiazheeeee** [comment]
Reviewed by the team during lesson.

**Comment by xAdwww** [comment]
Reviewed and closed.
