### ISSUE TITLE
Add a border to the Image for the Figure 2

### ISSUE THREAD

**Issue by jiazheeeee** [jiazheeeee/ICT-2201-Team-Project-Pharmacy-Shop-Work-Management-System#33]
Add Image Border for Figure No 2, since the Image seems like multiple image.

**Comment by xAdwww** [comment]
Done 16 Oct 2022

![Image](https://user-images.githubusercontent.com/90139442/196033851-f4eda23d-0aa9-4c95-a9d1-3af5c95157de.png)

**Comment by jiazheeeee** [comment]
Reviewed by the team during lesson, thread closed.

**Comment by xAdwww** [comment]
Reviewed and closed.
