### ISSUE TITLE
Define it in General Manager, Manager, Assistant Manager to data dictionary

### ISSUE THREAD

**Issue by jiazheeeee** [jiazheeeee/ICT-2201-Team-Project-Pharmacy-Shop-Work-Management-System#35]
Add the difference between General Manager, Manager, Assistant Manager to data dictionary.

**Comment by mushroom-hat** [comment]
Added the difference between these 3 types of manager and their access levels in the data dictionary of M2 report.

**Comment by jiazheeeee** [comment]
Reviewed by the team during lesson.
