### ISSUE TITLE
Ensure to have an overall checker for things like report

### ISSUE THREAD

**Issue by mushroom-hat** [jiazheeeee/ICT-2201-Team-Project-Pharmacy-Shop-Work-Management-System#36]

**Comment by mushroom-hat** [comment]
Currently, some items are not in sync due to task allocation to different group members (i.e., Use case description and use case diagram have some slight differences). Need to double check thoroughly to ensure everyone is on the same page

**Comment by jiazheeeee** [comment]
Updated accordingly to the requirements.

**Comment by ruihengg** [comment]
Reviewed and ready to close!

**Comment by mushroom-hat** [comment]
Reviewed by Ruiheng and I
