### ISSUE TITLE
Incorrect placement of assumption #1

### ISSUE THREAD

**Issue by mushroom-hat** [jiazheeeee/ICT-2201-Team-Project-Pharmacy-Shop-Work-Management-System#37]

**Comment by mushroom-hat** [comment]
Assumption #1 is supposed to put in non-functional requirement.

**Comment by jiazheeeee** [comment]
Completed. I have move the Assumption 1 to non functional requirements.

**Comment by mushroom-hat** [comment]
reviewed and closed.
