### ISSUE TITLE
Include more assumptions

### ISSUE THREAD

**Issue by mushroom-hat** [jiazheeeee/ICT-2201-Team-Project-Pharmacy-Shop-Work-Management-System#38]

**Comment by mushroom-hat** [comment]
Can include more assumptions such as assuming the fixed availability of staff. (I.e., availability cannot be changed after indication)

**Comment by jiazheeeee** [comment]
Added more assumptions in the M1 Report.

**Comment by mushroom-hat** [comment]
reviewed and closed
