### ISSUE TITLE
1.6.1.5. Missing duration estimation

### ISSUE THREAD

**Issue by mushroom-hat** [jiazheeeee/ICT-2201-Team-Project-Pharmacy-Shop-Work-Management-System#39]

**Comment by mushroom-hat** [comment]
Estimation for duration is missing. No pessimistic and optimistic. Need explain what the estimation value means whether it is doable or not.

**Comment by xAdwww** [comment]
Make use of this formula to calculate the duration.

![Image](https://user-images.githubusercontent.com/90139442/196035530-c306c9ee-b158-4d37-ba95-5477a1bc2903.png)

**Comment by mushroom-hat** [comment]
Noted with thanks Adwin, I will add the task durations for future tasks after we finished the high priority tasks.

**Comment by mushroom-hat** [comment]
I will also add the proper size estimations (UFP)

**Comment by xAdwww** [comment]
Reviewed all seems good!

29 October 2022
