### ISSUE TITLE
1.3.3. Clarify with client the functional and non-functional requirements using requirements gathering technique to ensure both on the same page.

### ISSUE THREAD

**Issue by xAdwww** [jiazheeeee/ICT-2201-Team-Project-Pharmacy-Shop-Work-Management-System#4]
On 13th Sept 2022 verify with client whether our requirements and assumptions are in the right direction.

**Comment by xAdwww** [comment]
Done on 13th Sept 2022 with the use of different elicitation methods such as interviews, prototyping and questionnaires.

**Comment by jiazheeeee** [comment]
Reviewed by the team during lab lesson.

**Comment by xAdwww** [comment]
Reviewed and closed.
