### ISSUE TITLE
1.4.2. Redefine Non-Functional Requirement (#UIR1)

### ISSUE THREAD

**Issue by jiazheeeee** [jiazheeeee/ICT-2201-Team-Project-Pharmacy-Shop-Work-Management-System#42]
Redefine the English language used.

**Comment by xAdwww** [comment]
Made relevant changes to the requirements that are feedbacked during M1.

![Image](https://user-images.githubusercontent.com/90139442/196035365-21d0e3d4-e074-4b46-88e2-a82cd903aa29.png)

**Comment by jiazheeeee** [comment]
Reviewed, thread closed.
