### ISSUE TITLE
1.8 Add chosen software architectural design pattern

### ISSUE THREAD

**Issue by mushroom-hat** [jiazheeeee/ICT-2201-Team-Project-Pharmacy-Shop-Work-Management-System#44]

**Comment by xAdwww** [comment]
Done the MVC software architectural design that we are utilizing

20 October 2022

![Image](https://user-images.githubusercontent.com/90139442/196970402-b5a182eb-a888-4a7f-bbd8-779677a8d459.png)

**Comment by xAdwww** [comment]
An example of MVC in the form of our project PharmaC with manager allocating job to staff

20 October 2022

![Image](https://user-images.githubusercontent.com/90139442/196971203-b3a5ee99-4fe1-4aff-8f86-50179511a12f.png)

**Comment by xAdwww** [comment]
reviewed, closing this issue.

29 October 2022
