### ISSUE TITLE
Add chosen design patterns to adopt

### ISSUE THREAD

**Issue by xAdwww** [jiazheeeee/ICT-2201-Team-Project-Pharmacy-Shop-Work-Management-System#45]
Choose design patterns to adopt into our project which was discuss in class.

**Comment by xAdwww** [comment]
Factory design pattern example done. Do take a look into Observer and singleton if they are applicable?

20 October 2022

![Image](https://user-images.githubusercontent.com/90139442/196970996-1224a380-dec4-4faf-8d8f-ffc50f49ac94.png)

**Comment by xAdwww** [comment]
Observer pattern added into M2 report.

29 October 2022

**Comment by mushroom-hat** [comment]
Reviewed.

**Comment by xAdwww** [comment]
Closing issue.

29 October 2022
