### ISSUE TITLE
1.9.2 Complete Milestone 2 Report

### ISSUE THREAD

**Issue by ruihengg** [jiazheeeee/ICT-2201-Team-Project-Pharmacy-Shop-Work-Management-System#46]
Milestone 2 Report to be vetted and proof read by the team before submission

**Comment by jiazheeeee** [comment]
We have to complete and submit the M2 Report by 29/10/2022

**Comment by mushroom-hat** [comment]
As of 1239, 29th October 2022, we are left with formatting of report and individual reflections.

**Comment by jiazheeeee** [comment]
Submitted
