### ISSUE TITLE
1.9.1. Add and Update Improvements from M1

### ISSUE THREAD

**Issue by ruihengg** [jiazheeeee/ICT-2201-Team-Project-Pharmacy-Shop-Work-Management-System#47]
Work on the M2 Report:
- Make improvements to M1 Report
- Add the class diagrams and charts
- Clean up Use case descriptions and etc

**Comment by jiazheeeee** [comment]
I have updated M1 Report. Please take a look at the review changes.

**Comment by mushroom-hat** [comment]
Added class, sequence and component diagrams.

**Comment by xAdwww** [comment]
Made improvements to M1 report Cleaned up the use case descriptions.

29 October 2022

**Comment by ruihengg** [comment]
Reviewed and closed.
