### ISSUE TITLE
1.11.1. Conduct Black-box Testing

### ISSUE THREAD

**Issue by mushroom-hat** [jiazheeeee/ICT-2201-Team-Project-Pharmacy-Shop-Work-Management-System#50]

**Comment by xAdwww** [comment]
Created the State diagram to help aid in the process of creating Equivalence Partitioning, Boundary Value Analysis & decision table 

24 November 2022


![Image](https://user-images.githubusercontent.com/90139442/203795144-da64eeae-34fa-45dc-b690-97f355e46830.png)

**Comment by ruihengg** [comment]
Equivalence Partitioning, Boundary Value Analysis and Decision Tables are used to perform and create test cases for black box testing

![Image](https://user-images.githubusercontent.com/97569209/203824767-0291d293-3c17-4e55-9600-49687224d797.png)

![Image](https://user-images.githubusercontent.com/97569209/203824827-ce65955a-59fb-4607-bcb9-b86f5fc90e2a.png)

![Image](https://user-images.githubusercontent.com/97569209/203824873-5c81603b-46dd-4a27-bcab-159a13a93927.png)

**Comment by mushroom-hat** [comment]
Looks good!

**Comment by xAdwww** [comment]
Done and reviewed good to go!

**Comment by ruihengg** [comment]
Looking great! Ready to go!

**Comment by mushroom-hat** [comment]
Thanks all, everyone played a great role in this black box testing :)
