### ISSUE TITLE
1.10.2 Create prototypes of expected product

### ISSUE THREAD

**Issue by xAdwww** [jiazheeeee/ICT-2201-Team-Project-Pharmacy-Shop-Work-Management-System#57]
Create prototypes of the final product to be expected as required from M3

**Comment by jiazheeeee** [comment]
Login Page


![Image](https://user-images.githubusercontent.com/88085142/204095128-f726c62a-eb3c-4b84-a440-7dcf831b7f43.png)

**Comment by jiazheeeee** [comment]
Manager Landing Page


![Image](https://user-images.githubusercontent.com/88085142/204095148-2465b367-669a-41f7-b278-da32b23ada70.png)

**Comment by jiazheeeee** [comment]
IT Admin Landing Page


![Image](https://user-images.githubusercontent.com/88085142/204095162-08ccb73d-2f0a-4f3b-8659-af7e860f2c4f.png)

**Comment by jiazheeeee** [comment]
Staff Landing Page


![Image](https://user-images.githubusercontent.com/88085142/204095178-27b26efd-f282-4ba3-9c38-ed4e4639e91a.png)

**Comment by jiazheeeee** [comment]
The team have completed the entire prototype wireframe. Please refer to the M3 Report to view the full prototype. Completed by the team.

**Comment by ruihengg** [comment]
Looks great. Reviewed and ready to close!
